version: '3'


services:
  elecciones-micro:
    build: ../elecciones-parcialII
    image: elecciones-app
    ports:
      - "8084:8080"
    environment:
      APP_NAME: elecciones-app
    depends_on:
      - apiExterna
    networks:
      - elecciones-network

  apiExterna:
    image: tupfrcutn/elecciones-2023:1.0.0
    ports:
      - "8080:8080"
    networks:
      - elecciones-network

networks:
  elecciones-network:
    driver: bridge
